dist: bionic

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y squashfs-tools xorriso syslinux-common

script:
  - sudo ./build.sh

after_success:
  - sudo chmod a+rw nitruxos.iso
  - sh ./upload.sh

branches:
  except:
    - /^(?i:continuous)$/

notifications:
  email: false
